nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
mysql:
  image: mysql:latest
  expose:
    - "3306"
  ports:
    - "3307:3306"
  environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: admin123
    MYSQL_USER: xmaple
    MYSQL_PASSWORD: ""
